import { fileURLToPath } from "node:url";

import react from "@vitejs/plugin-react";
import { defineConfig, type Plugin } from "vitest/config";

const engineRoot = fileURLToPath(new URL("../src", import.meta.url));

/**
 * Emits the offline service worker with the real build manifest baked in.
 *
 * Written by hand rather than pulled from a plugin: the caching policy this
 * product needs is one sentence long (precache everything, serve from cache,
 * never touch the network at runtime) and a generated worker would be harder
 * to audit against the "no runtime network dependency" requirement than to
 * read.
 */
function offlineServiceWorker(): Plugin {
  return {
    name: "mahjong-offline-sw",
    apply: "build",
    generateBundle(_options, bundle) {
      const assets = Object.keys(bundle)
        .filter((name) => !name.endsWith(".map"))
        .map((name) => `./${name}`);
      const precache = [
        "./",
        "./index.html",
        "./manifest.webmanifest",
        "./icons/icon.svg",
        "./icons/icon-192.png",
        "./icons/icon-512.png",
        "./icons/icon-maskable-512.png",
        ...assets,
      ];
      // The cache name carries the content hashes, so a new build installs a
      // new cache and the old one is dropped on activate.
      const version = assets.join("|").length.toString(36) + assets.length.toString(36);

      this.emitFile({
        type: "asset",
        fileName: "sw.js",
        source: `/* Generated by vite.config.ts. Do not edit. */
const CACHE = "mahjong-v${version}";
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
      .then(() => self.clients.claim()),
  );
});

/*
 * Cache first, and for navigations fall back to the cached shell rather than
 * to the network. The game has no backend and no runtime network dependency:
 * once installed, being offline is not a degraded mode, it is the normal one.
 */
self.addEventListener("fetch", (event) => {
  const request = event.request;
  if (request.method !== "GET") return;
  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      if (request.mode === "navigate") {
        return caches.match("./index.html").then((shell) => shell || fetch(request));
      }
      return fetch(request).catch(() => Response.error());
    }),
  );
});
`,
      });
    },
  };
}

// The production app and the headless engine share one source tree. The engine
// is imported directly rather than through a build artefact so that a rules or
// bot change cannot silently diverge from what the table plays.
// Capacitor bundles the build into the native app and serves it from the
// webview's own root, not from a GitHub Pages subpath — a root-relative
// "/mahjong/…" asset URL 404s there. `npm run build:capacitor` (#11) sets
// this so the same build tooling can target either host correctly.
const capacitorBuild = process.env.CAPACITOR_BUILD === "1";

export default defineConfig(({ command, isPreview }) => ({
  // GitHub Pages serves project sites from /<repo>/. Preview has to agree with
  // build or it serves a shell whose asset URLs it cannot resolve; only the dev
  // server stays at the root, where the phone-over-LAN workflow expects it.
  base: capacitorBuild ? "./" : command === "build" || isPreview === true ? "/mahjong/" : "/",
  plugins: [react(), offlineServiceWorker()],
  resolve: {
    alias: [
      { find: /^@engine$/, replacement: `${engineRoot}/index.ts` },
      { find: /^@engine\//, replacement: `${engineRoot}/` },
    ],
  },
  server: {
    host: true,
    port: 5174,
    strictPort: true,
    // The rules reference (#9) imports docs/HKOS_RULES.md as raw text, one
    // directory above this app's root, for the same reason the engine is
    // imported directly from ../src: so it can never silently drift from the
    // document it is meant to match exactly.
    fs: { allow: [fileURLToPath(new URL("..", import.meta.url))] },
  },
  preview: { host: true, port: 4174, strictPort: true },
  test: {
    environment: "jsdom",
    include: ["src/**/*.test.ts", "src/**/*.test.tsx"],
    setupFiles: ["./src/test/setup.ts"],
  },
}));
